/* Generated By:JavaCC: Do not edit this line. AdilTreeConstants.java Version 7.0.10 */
package edu.sdsc.adil;

public interface AdilTreeConstants
{
  public int JJTADILSTATEMENT = 0;
  public int JJTSTATEMENT = 1;
  public int JJTUSECLAUSE = 2;
  public int JJTIMPORTLIBRARY = 3;
  public int JJTCREATEANALYSIS = 4;
  public int JJTREPORTSTATEMENT = 5;
  public int JJTSTORESTATEMENT = 6;
  public int JJTASSIGNMENTSTATEMENT = 7;
  public int JJTRETURNSTATEMENT = 8;
  public int JJTPROPERTYGRAPH = 9;
  public int JJTGRAPHNODE = 10;
  public int JJTGRAPHEDGE = 11;
  public int JJTCONSTRUCTGRAPHFROMRELATIONEXPRESSION = 12;
  public int JJTCONSTRUCTGRAPHFROMRELATIONFUNC = 13;
  public int JJTCONSTRUCTGRAPH = 14;
  public int JJTPROPERTYCONSTRAINT = 15;
  public int JJTNODEEXPRESSIONCONSTRAINT = 16;
  public int JJTCREATEPROPERTY = 17;
  public int JJTCREATESETSTATEMENT = 18;
  public int JJTCREATENODESTATEMENT = 19;
  public int JJTCREATEEDGESTATEMENT = 20;
  public int JJTCREATEVIEWSTATEMENT = 21;
  public int JJTGETFUNCTION = 22;
  public int JJTAWSMFUNCTION = 23;
  public int JJTRANGEELEMENT = 24;
  public int JJTLISTCREATION = 25;
  public int JJTFILTERASSIGNMENT = 26;
  public int JJTWHEREEXPRESSION = 27;
  public int JJTPROPERTY = 28;
  public int JJTNODEEXPRESSION = 29;
  public int JJTPATHEXPRESSION = 30;
  public int JJTCYPHERSTATEMENT = 31;
  public int JJTMAPEXPRESSION = 32;
  public int JJTREDUCEEXPRESSION = 33;
  public int JJTDBPASS = 34;
  public int JJTQUETEDSTATEMENT = 35;
  public int JJTCYPHERSCHEMA = 36;
  public int JJTCYPHEREXPRESSION = 37;
  public int JJTCYPHERPASS = 38;
  public int JJTCYPHERFORMAP = 39;
  public int JJTSOLRPASS = 40;
  public int JJTSQLEXPRESSION = 41;
  public int JJTSQLPASS = 42;
  public int JJTMATRIXASSIGNMENT = 43;
  public int JJTLITERALASSIGNMENT = 44;
  public int JJTMATHASSIGNMENT = 45;
  public int JJTMATHEXPRESSION = 46;
  public int JJTTUPLEASSIGNMENT = 47;
  public int JJTTUPLEEXTRACTION = 48;
  public int JJTLISTASSIGNMENT = 49;
  public int JJTSTRINGASSIGNMENT = 50;
  public int JJTLISTELEMENT = 51;
  public int JJTLISTEXPRESSION = 52;
  public int JJTEXPRSFORLAMBDA = 53;
  public int JJTEXPRSFORLAMBDADETAIL = 54;
  public int JJTGETLAMBDAFUNCTION = 55;
  public int JJTLAMBDAFUNCTIONEXPRSSION = 56;
  public int JJTEXPRESSION = 57;


  public String[] jjtNodeName = {
    "ADILStatement",
    "Statement",
    "UseClause",
    "ImportLibrary",
    "CreateAnalysis",
    "ReportStatement",
    "StoreStatement",
    "AssignmentStatement",
    "ReturnStatement",
    "PropertyGraph",
    "GRAPHNODE",
    "GRAPHEDGE",
    "ConstructGraphFromRelationExpression",
    "ConstructGraphFromRelationFunc",
    "ConstructGraph",
    "propertyConstraint",
    "NodeExpressionConstraint",
    "createProperty",
    "CreateSetStatement",
    "createNodeStatement",
    "createEdgeStatement",
    "CreateViewStatement",
    "GetFunction",
    "AWSMFunction",
    "rangeElement",
    "ListCreation",
    "FilterAssignment",
    "WhereExpression",
    "property",
    "NodeExpression",
    "PathExpression",
    "CypherStatement",
    "MapExpression",
    "ReduceExpression",
    "DBPASS",
    "quetedStatement",
    "CypherSchema",
    "CypherExpression",
    "CYPHERPASS",
    "CypherForMap",
    "SOLRPASS",
    "SQLExpression",
    "SQLPASS",
    "MATRIXASSIGNMENT",
    "LITERALASSIGNMENT",
    "MATHASSIGNMENT",
    "MATHEXPRESSION",
    "TUPLEASSIGNMENT",
    "TUPLEEXTRACTION",
    "LISTASSIGNMENT",
    "STRINGASSIGNMENT",
    "ListElement",
    "LISTEXPRESSION",
    "exprsforLambda",
    "exprsforLambdaDetail",
    "GetLambdaFunction",
    "LambdaFunctionExprssion",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=5837e35957bdd8c8c5782ae2841a558a (do not edit this line) */
