/* Generated By:JJTree: Do not edit this line. ASTcreateEdgeStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTcreateEdgeStatement extends SimpleNode {
  public ASTcreateEdgeStatement(int id) {
    super(id);
  }

  public ASTcreateEdgeStatement(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6d8e683fefbf2ef7a2edf4e66eb1d1c1 (do not edit this line) */
