/* Generated By:JJTree: Do not edit this line. ASTCYPHERPASS.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCYPHERPASS extends SimpleNode {
  public ASTCYPHERPASS(int id) {
    super(id);
  }

  public ASTCYPHERPASS(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a7b909b1f781d6063127260c64a47fb1 (do not edit this line) */
