/* Generated By:JJTree: Do not edit this line. ASTConstructGraph.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTConstructGraph extends SimpleNode {
  public ASTConstructGraph(int id) {
    super(id);
  }

  public ASTConstructGraph(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ede28d64cfed08d7d87460b8fdab62dd (do not edit this line) */
