/* Generated By:JJTree: Do not edit this line. ASTcreateProperty.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTcreateProperty extends SimpleNode {
  public ASTcreateProperty(int id) {
    super(id);
  }

  public ASTcreateProperty(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ac167e00c195d6ed8a7d9df0cebbedc7 (do not edit this line) */
