/* Generated By:JJTree: Do not edit this line. ASTCypherForMap.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCypherForMap extends SimpleNode {
  public ASTCypherForMap(int id) {
    super(id);
  }

  public ASTCypherForMap(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=08171163160e7858f8cc284975517d80 (do not edit this line) */
