/* Generated By:JJTree: Do not edit this line. ASTCypherExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTCypherExpression extends SimpleNode {
  public ASTCypherExpression(int id) {
    super(id);
  }

  public ASTCypherExpression(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7dcdb8ed2dd3634f61371cd2e22d6c51 (do not edit this line) */
