/* Generated By:JJTree: Do not edit this line. ASTDBPASS.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTDBPASS extends SimpleNode {
  public ASTDBPASS(int id) {
    super(id);
  }

  public ASTDBPASS(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cd44c3e1d52e287d4e82984a6c3f3efa (do not edit this line) */
