/* Generated By:JJTree: Do not edit this line. ASTexprsforLambdaDetail.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTexprsforLambdaDetail extends SimpleNode {
  public ASTexprsforLambdaDetail(int id) {
    super(id);
  }

  public ASTexprsforLambdaDetail(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b96fb5154f3228b8d4911eb7f81f27c4 (do not edit this line) */
