/* Generated By:JJTree: Do not edit this line. ASTexprsforLambda.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTexprsforLambda extends SimpleNode {
  public ASTexprsforLambda(int id) {
    super(id);
  }

  public ASTexprsforLambda(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ffa600011ea18451168b2c8331dbf96 (do not edit this line) */
