/* Generated By:JJTree: Do not edit this line. ASTFilterAssignment.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTFilterAssignment extends SimpleNode {
  public ASTFilterAssignment(int id) {
    super(id);
  }

  public ASTFilterAssignment(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b1b1ba54a90cd8a10207067e1b08567 (do not edit this line) */
