/* Generated By:JJTree: Do not edit this line. ASTLITERALASSIGNMENT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTLITERALASSIGNMENT extends SimpleNode {
  public ASTLITERALASSIGNMENT(int id) {
    super(id);
  }

  public ASTLITERALASSIGNMENT(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c12d0818be198b7eb10c70052dcca8dd (do not edit this line) */
