/* Generated By:JJTree: Do not edit this line. ASTLISTASSIGNMENT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTLISTASSIGNMENT extends SimpleNode {
  public ASTLISTASSIGNMENT(int id) {
    super(id);
  }

  public ASTLISTASSIGNMENT(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f503eda505a774f4e07d034cb031cd60 (do not edit this line) */
