/* Generated By:JJTree: Do not edit this line. ASTLambdaFunctionExprssion.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTLambdaFunctionExprssion extends SimpleNode {
  public ASTLambdaFunctionExprssion(int id) {
    super(id);
  }

  public ASTLambdaFunctionExprssion(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c93228c53bc093acd51d6866f64dc538 (do not edit this line) */
