/* Generated By:JJTree: Do not edit this line. ASTMATRIXASSIGNMENT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTMATRIXASSIGNMENT extends SimpleNode {
  public ASTMATRIXASSIGNMENT(int id) {
    super(id);
  }

  public ASTMATRIXASSIGNMENT(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2f750620cc70978efcbe225fc9662de (do not edit this line) */
