/* Generated By:JJTree: Do not edit this line. ASTMATHASSIGNMENT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTMATHASSIGNMENT extends SimpleNode {
  public ASTMATHASSIGNMENT(int id) {
    super(id);
  }

  public ASTMATHASSIGNMENT(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=239a44a75e69b23907847db9d5f513c6 (do not edit this line) */
