/* Generated By:JJTree: Do not edit this line. ASTMATHEXPRESSION.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTMATHEXPRESSION extends SimpleNode {
  public ASTMATHEXPRESSION(int id) {
    super(id);
  }

  public ASTMATHEXPRESSION(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b29df6dfbed871cc956514f5107f1653 (do not edit this line) */
