/* Generated By:JJTree: Do not edit this line. ASTNodeExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTNodeExpression extends SimpleNode {
  public ASTNodeExpression(int id) {
    super(id);
  }

  public ASTNodeExpression(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4756a9af54aa1c51f5f8bdcf4d1219e9 (do not edit this line) */
