/* Generated By:JJTree: Do not edit this line. ASTNodeExpressionConstraint.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTNodeExpressionConstraint extends SimpleNode {
  public ASTNodeExpressionConstraint(int id) {
    super(id);
  }

  public ASTNodeExpressionConstraint(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=deca5d1264554652abef9f68a1ddaf30 (do not edit this line) */
