/* Generated By:JJTree: Do not edit this line. ASTPropertyGraph.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTPropertyGraph extends SimpleNode {
  public ASTPropertyGraph(int id) {
    super(id);
  }

  public ASTPropertyGraph(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f2099d86a98fcfa7ee7aa9cdcf5c5267 (do not edit this line) */
