/* Generated By:JJTree: Do not edit this line. ASTpropertyConstraint.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTpropertyConstraint extends SimpleNode {
  public ASTpropertyConstraint(int id) {
    super(id);
  }

  public ASTpropertyConstraint(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2c5a0b7ca841ac3e4565b806021ad29c (do not edit this line) */
