/* Generated By:JJTree: Do not edit this line. ASTrangeElement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTrangeElement extends SimpleNode {
  public ASTrangeElement(int id) {
    super(id);
  }

  public ASTrangeElement(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0b092a0ff037a51250834ffa96e0d2a7 (do not edit this line) */
