/* Generated By:JJTree: Do not edit this line. ASTSQLExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTSQLExpression extends SimpleNode {
  public ASTSQLExpression(int id) {
    super(id);
  }

  public ASTSQLExpression(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=47771ecfc64dfb34b511aa306d6a0328 (do not edit this line) */
