/* Generated By:JJTree: Do not edit this line. ASTSOLRPASS.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTSOLRPASS extends SimpleNode {
  public ASTSOLRPASS(int id) {
    super(id);
  }

  public ASTSOLRPASS(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1734a721dfadcd185dbaa34b01e121bc (do not edit this line) */
