/* Generated By:JJTree: Do not edit this line. ASTTUPLEEXTRACTION.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTTUPLEEXTRACTION extends SimpleNode {
  public ASTTUPLEEXTRACTION(int id) {
    super(id);
  }

  public ASTTUPLEEXTRACTION(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e4a3023a1c1eeb5c77932044fdf0ace0 (do not edit this line) */
