/* Generated By:JJTree: Do not edit this line. ASTTUPLEASSIGNMENT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sdsc.adil;

public
class ASTTUPLEASSIGNMENT extends SimpleNode {
  public ASTTUPLEASSIGNMENT(int id) {
    super(id);
  }

  public ASTTUPLEASSIGNMENT(Adil p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AdilVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=99480ffc7ff4734d8cb046d9b5fa8a91 (do not edit this line) */
